// Sample policies
let samplePolicies = [
  {
    name: "LIC Jeevan Suraksha 1",
    type: "life",
    premium: 5000,
    coverage: 300000,
    riskLevel: "low",
    provider: "LIC",
  },
  {
    name: "HDFC Life Shield 2",
    type: "life",
    premium: 5200,
    coverage: 320000,
    riskLevel: "medium",
    provider: "HDFC Life",
  },
  {
    name: "ICICI Life Secure 3",
    type: "life",
    premium: 5400,
    coverage: 340000,
    riskLevel: "high",
    provider: "ICICI Prudential",
  },
  {
    name: "Max Life Protect 4",
    type: "life",
    premium: 5600,
    coverage: 360000,
    riskLevel: "low",
    provider: "Max Life",
  },
  {
    name: "SBI Life Cover 5",
    type: "life",
    premium: 5800,
    coverage: 380000,
    riskLevel: "medium",
    provider: "SBI Life",
  },
  {
    name: "LIC Jeevan Anand 6",
    type: "life",
    premium: 6000,
    coverage: 400000,
    riskLevel: "high",
    provider: "LIC",
  },
  {
    name: "HDFC Smart Life 7",
    type: "life",
    premium: 6200,
    coverage: 420000,
    riskLevel: "low",
    provider: "HDFC Life",
  },
  {
    name: "ICICI Future Secure 8",
    type: "life",
    premium: 6400,
    coverage: 440000,
    riskLevel: "medium",
    provider: "ICICI Prudential",
  },
  {
    name: "Max Life Growth 9",
    type: "life",
    premium: 6600,
    coverage: 460000,
    riskLevel: "high",
    provider: "Max Life",
  },
  {
    name: "SBI Life Plus 10",
    type: "life",
    premium: 6800,
    coverage: 480000,
    riskLevel: "low",
    provider: "SBI Life",
  },
  {
    name: "LIC Wealth Protect 11",
    type: "life",
    premium: 7000,
    coverage: 500000,
    riskLevel: "medium",
    provider: "LIC",
  },
  {
    name: "HDFC Life Advantage 12",
    type: "life",
    premium: 7200,
    coverage: 520000,
    riskLevel: "high",
    provider: "HDFC Life",
  },
  {
    name: "ICICI Life Guard 13",
    type: "life",
    premium: 7400,
    coverage: 540000,
    riskLevel: "low",
    provider: "ICICI Prudential",
  },
  {
    name: "Max Life Elite 14",
    type: "life",
    premium: 7600,
    coverage: 560000,
    riskLevel: "medium",
    provider: "Max Life",
  },
  {
    name: "SBI Life Smart 15",
    type: "life",
    premium: 7800,
    coverage: 580000,
    riskLevel: "high",
    provider: "SBI Life",
  },
  {
    name: "LIC Jeevan Plus 16",
    type: "life",
    premium: 8000,
    coverage: 600000,
    riskLevel: "low",
    provider: "LIC",
  },
  {
    name: "HDFC Life Secure 17",
    type: "life",
    premium: 8200,
    coverage: 620000,
    riskLevel: "medium",
    provider: "HDFC Life",
  },
  {
    name: "ICICI Life Growth 18",
    type: "life",
    premium: 8400,
    coverage: 640000,
    riskLevel: "high",
    provider: "ICICI Prudential",
  },
  {
    name: "Max Life Prime 19",
    type: "life",
    premium: 8600,
    coverage: 660000,
    riskLevel: "low",
    provider: "Max Life",
  },
  {
    name: "SBI Life Secure 20",
    type: "life",
    premium: 8800,
    coverage: 680000,
    riskLevel: "medium",
    provider: "SBI Life",
  },
  {
    name: "LIC Life Plan 21",
    type: "life",
    premium: 9000,
    coverage: 700000,
    riskLevel: "high",
    provider: "LIC",
  },
  {
    name: "HDFC Life Plan 22",
    type: "life",
    premium: 9200,
    coverage: 720000,
    riskLevel: "low",
    provider: "HDFC Life",
  },
  {
    name: "ICICI Life Plan 23",
    type: "life",
    premium: 9400,
    coverage: 740000,
    riskLevel: "medium",
    provider: "ICICI Prudential",
  },
  {
    name: "Max Life Plan 24",
    type: "life",
    premium: 9600,
    coverage: 760000,
    riskLevel: "high",
    provider: "Max Life",
  },
  {
    name: "SBI Life Plan 25",
    type: "life",
    premium: 9800,
    coverage: 780000,
    riskLevel: "low",
    provider: "SBI Life",
  },
  {
    name: "LIC Life Plan 26",
    type: "life",
    premium: 10000,
    coverage: 800000,
    riskLevel: "medium",
    provider: "LIC",
  },
  {
    name: "HDFC Life Plan 27",
    type: "life",
    premium: 10200,
    coverage: 820000,
    riskLevel: "high",
    provider: "HDFC Life",
  },
  {
    name: "ICICI Life Plan 28",
    type: "life",
    premium: 10400,
    coverage: 840000,
    riskLevel: "low",
    provider: "ICICI Prudential",
  },
  {
    name: "Max Life Plan 29",
    type: "life",
    premium: 10600,
    coverage: 860000,
    riskLevel: "medium",
    provider: "Max Life",
  },
  {
    name: "SBI Life Plan 30",
    type: "life",
    premium: 10800,
    coverage: 880000,
    riskLevel: "high",
    provider: "SBI Life",
  },
  {
    name: "LIC Life Plan 31",
    type: "life",
    premium: 11000,
    coverage: 900000,
    riskLevel: "low",
    provider: "LIC",
  },
  {
    name: "HDFC Life Plan 32",
    type: "life",
    premium: 11200,
    coverage: 920000,
    riskLevel: "medium",
    provider: "HDFC Life",
  },
  {
    name: "ICICI Life Plan 33",
    type: "life",
    premium: 11400,
    coverage: 940000,
    riskLevel: "high",
    provider: "ICICI Prudential",
  },
  {
    name: "Max Life Plan 34",
    type: "life",
    premium: 11600,
    coverage: 960000,
    riskLevel: "low",
    provider: "Max Life",
  },
  {
    name: "SBI Life Plan 35",
    type: "life",
    premium: 11800,
    coverage: 980000,
    riskLevel: "medium",
    provider: "SBI Life",
  },
  {
    name: "LIC Life Plan 36",
    type: "life",
    premium: 12000,
    coverage: 1000000,
    riskLevel: "high",
    provider: "LIC",
  },
  {
    name: "HDFC Life Plan 37",
    type: "life",
    premium: 12200,
    coverage: 1020000,
    riskLevel: "low",
    provider: "HDFC Life",
  },
  {
    name: "ICICI Life Plan 38",
    type: "life",
    premium: 12400,
    coverage: 1040000,
    riskLevel: "medium",
    provider: "ICICI Prudential",
  },
  {
    name: "Max Life Plan 39",
    type: "life",
    premium: 12600,
    coverage: 1060000,
    riskLevel: "high",
    provider: "Max Life",
  },
  {
    name: "SBI Life Plan 40",
    type: "life",
    premium: 12800,
    coverage: 1080000,
    riskLevel: "low",
    provider: "SBI Life",
  },
  {
    name: "LIC Life Plan 41",
    type: "life",
    premium: 13000,
    coverage: 1100000,
    riskLevel: "medium",
    provider: "LIC",
  },
  {
    name: "HDFC Life Plan 42",
    type: "life",
    premium: 13200,
    coverage: 1120000,
    riskLevel: "high",
    provider: "HDFC Life",
  },
  {
    name: "ICICI Life Plan 43",
    type: "life",
    premium: 13400,
    coverage: 1140000,
    riskLevel: "low",
    provider: "ICICI Prudential",
  },
  {
    name: "Max Life Plan 44",
    type: "life",
    premium: 13600,
    coverage: 1160000,
    riskLevel: "medium",
    provider: "Max Life",
  },
  {
    name: "SBI Life Plan 45",
    type: "life",
    premium: 13800,
    coverage: 1180000,
    riskLevel: "high",
    provider: "SBI Life",
  },
  {
    name: "LIC Life Plan 46",
    type: "life",
    premium: 14000,
    coverage: 1200000,
    riskLevel: "low",
    provider: "LIC",
  },
  {
    name: "HDFC Life Plan 47",
    type: "life",
    premium: 14200,
    coverage: 1220000,
    riskLevel: "medium",
    provider: "HDFC Life",
  },
  {
    name: "ICICI Life Plan 48",
    type: "life",
    premium: 14400,
    coverage: 1240000,
    riskLevel: "high",
    provider: "ICICI Prudential",
  },
  {
    name: "Max Life Plan 49",
    type: "life",
    premium: 14600,
    coverage: 1260000,
    riskLevel: "low",
    provider: "Max Life",
  },
  {
    name: "SBI Life Plan 50",
    type: "life",
    premium: 14800,
    coverage: 1280000,
    riskLevel: "medium",
    provider: "SBI Life",
  },

  {
    name: "Star Health Suraksha 1",
    type: "health",
    premium: 3000,
    coverage: 150000,
    riskLevel: "low",
    provider: "Star Health",
  },
  {
    name: "Niva Bupa Care 2",
    type: "health",
    premium: 3200,
    coverage: 170000,
    riskLevel: "medium",
    provider: "Niva Bupa",
  },
  {
    name: "Care Health Shield 3",
    type: "health",
    premium: 3400,
    coverage: 190000,
    riskLevel: "high",
    provider: "Care Health",
  },
  {
    name: "Aditya Health Plan 4",
    type: "health",
    premium: 3600,
    coverage: 210000,
    riskLevel: "low",
    provider: "Aditya Birla Health",
  },
  {
    name: "Reliance Health Guard 5",
    type: "health",
    premium: 3800,
    coverage: 230000,
    riskLevel: "medium",
    provider: "Reliance Health",
  },
  {
    name: "Health Plan 6",
    type: "health",
    premium: 4000,
    coverage: 250000,
    riskLevel: "high",
    provider: "Star Health",
  },
  {
    name: "Health Plan 7",
    type: "health",
    premium: 4200,
    coverage: 270000,
    riskLevel: "low",
    provider: "Niva Bupa",
  },
  {
    name: "Health Plan 8",
    type: "health",
    premium: 4400,
    coverage: 290000,
    riskLevel: "medium",
    provider: "Care Health",
  },
  {
    name: "Health Plan 9",
    type: "health",
    premium: 4600,
    coverage: 310000,
    riskLevel: "high",
    provider: "Aditya Birla Health",
  },
  {
    name: "Health Plan 10",
    type: "health",
    premium: 4800,
    coverage: 330000,
    riskLevel: "low",
    provider: "Reliance Health",
  },
  {
    name: "Health Plan 11",
    type: "health",
    premium: 5000,
    coverage: 350000,
    riskLevel: "medium",
    provider: "Star Health",
  },
  {
    name: "Health Plan 12",
    type: "health",
    premium: 5200,
    coverage: 370000,
    riskLevel: "high",
    provider: "Niva Bupa",
  },
  {
    name: "Health Plan 13",
    type: "health",
    premium: 5400,
    coverage: 390000,
    riskLevel: "low",
    provider: "Care Health",
  },
  {
    name: "Health Plan 14",
    type: "health",
    premium: 5600,
    coverage: 410000,
    riskLevel: "medium",
    provider: "Aditya Birla Health",
  },
  {
    name: "Health Plan 15",
    type: "health",
    premium: 5800,
    coverage: 430000,
    riskLevel: "high",
    provider: "Reliance Health",
  },
  {
    name: "Health Plan 16",
    type: "health",
    premium: 6000,
    coverage: 450000,
    riskLevel: "low",
    provider: "Star Health",
  },
  {
    name: "Health Plan 17",
    type: "health",
    premium: 6200,
    coverage: 470000,
    riskLevel: "medium",
    provider: "Niva Bupa",
  },
  {
    name: "Health Plan 18",
    type: "health",
    premium: 6400,
    coverage: 490000,
    riskLevel: "high",
    provider: "Care Health",
  },
  {
    name: "Health Plan 19",
    type: "health",
    premium: 6600,
    coverage: 510000,
    riskLevel: "low",
    provider: "Aditya Birla Health",
  },
  {
    name: "Health Plan 20",
    type: "health",
    premium: 6800,
    coverage: 530000,
    riskLevel: "medium",
    provider: "Reliance Health",
  },
  {
    name: "Health Plan 21",
    type: "health",
    premium: 7000,
    coverage: 550000,
    riskLevel: "high",
    provider: "Star Health",
  },
  {
    name: "Health Plan 22",
    type: "health",
    premium: 7200,
    coverage: 570000,
    riskLevel: "low",
    provider: "Niva Bupa",
  },
  {
    name: "Health Plan 23",
    type: "health",
    premium: 7400,
    coverage: 590000,
    riskLevel: "medium",
    provider: "Care Health",
  },
  {
    name: "Health Plan 24",
    type: "health",
    premium: 7600,
    coverage: 610000,
    riskLevel: "high",
    provider: "Aditya Birla Health",
  },
  {
    name: "Health Plan 25",
    type: "health",
    premium: 7800,
    coverage: 630000,
    riskLevel: "low",
    provider: "Reliance Health",
  },
  {
    name: "Health Plan 26",
    type: "health",
    premium: 8000,
    coverage: 650000,
    riskLevel: "medium",
    provider: "Star Health",
  },
  {
    name: "Health Plan 27",
    type: "health",
    premium: 8200,
    coverage: 670000,
    riskLevel: "high",
    provider: "Niva Bupa",
  },
  {
    name: "Health Plan 28",
    type: "health",
    premium: 8400,
    coverage: 690000,
    riskLevel: "low",
    provider: "Care Health",
  },
  {
    name: "Health Plan 29",
    type: "health",
    premium: 8600,
    coverage: 710000,
    riskLevel: "medium",
    provider: "Aditya Birla Health",
  },
  {
    name: "Health Plan 30",
    type: "health",
    premium: 8800,
    coverage: 730000,
    riskLevel: "high",
    provider: "Reliance Health",
  },
  {
    name: "Health Plan 31",
    type: "health",
    premium: 9000,
    coverage: 750000,
    riskLevel: "low",
    provider: "Star Health",
  },
  {
    name: "Health Plan 32",
    type: "health",
    premium: 9200,
    coverage: 770000,
    riskLevel: "medium",
    provider: "Niva Bupa",
  },
  {
    name: "Health Plan 33",
    type: "health",
    premium: 9400,
    coverage: 790000,
    riskLevel: "high",
    provider: "Care Health",
  },
  {
    name: "Health Plan 34",
    type: "health",
    premium: 9600,
    coverage: 810000,
    riskLevel: "low",
    provider: "Aditya Birla Health",
  },
  {
    name: "Health Plan 35",
    type: "health",
    premium: 9800,
    coverage: 830000,
    riskLevel: "medium",
    provider: "Reliance Health",
  },
  {
    name: "Health Plan 36",
    type: "health",
    premium: 10000,
    coverage: 850000,
    riskLevel: "high",
    provider: "Star Health",
  },
  {
    name: "Health Plan 37",
    type: "health",
    premium: 10200,
    coverage: 870000,
    riskLevel: "low",
    provider: "Niva Bupa",
  },
  {
    name: "Health Plan 38",
    type: "health",
    premium: 10400,
    coverage: 890000,
    riskLevel: "medium",
    provider: "Care Health",
  },
  {
    name: "Health Plan 39",
    type: "health",
    premium: 10600,
    coverage: 910000,
    riskLevel: "high",
    provider: "Aditya Birla Health",
  },
  {
    name: "Health Plan 40",
    type: "health",
    premium: 10800,
    coverage: 930000,
    riskLevel: "low",
    provider: "Reliance Health",
  },
  {
    name: "Health Plan 41",
    type: "health",
    premium: 11000,
    coverage: 950000,
    riskLevel: "medium",
    provider: "Star Health",
  },
  {
    name: "Health Plan 42",
    type: "health",
    premium: 11200,
    coverage: 970000,
    riskLevel: "high",
    provider: "Niva Bupa",
  },
  {
    name: "Health Plan 43",
    type: "health",
    premium: 11400,
    coverage: 990000,
    riskLevel: "low",
    provider: "Care Health",
  },
  {
    name: "Health Plan 44",
    type: "health",
    premium: 11600,
    coverage: 1010000,
    riskLevel: "medium",
    provider: "Aditya Birla Health",
  },
  {
    name: "Health Plan 45",
    type: "health",
    premium: 11800,
    coverage: 1030000,
    riskLevel: "high",
    provider: "Reliance Health",
  },
  {
    name: "Health Plan 46",
    type: "health",
    premium: 12000,
    coverage: 1050000,
    riskLevel: "low",
    provider: "Star Health",
  },
  {
    name: "Health Plan 47",
    type: "health",
    premium: 12200,
    coverage: 1070000,
    riskLevel: "medium",
    provider: "Niva Bupa",
  },
  {
    name: "Health Plan 48",
    type: "health",
    premium: 12400,
    coverage: 1090000,
    riskLevel: "high",
    provider: "Care Health",
  },
  {
    name: "Health Plan 49",
    type: "health",
    premium: 12600,
    coverage: 1110000,
    riskLevel: "low",
    provider: "Aditya Birla Health",
  },
  {
    name: "Health Plan 50",
    type: "health",
    premium: 12800,
    coverage: 1130000,
    riskLevel: "medium",
    provider: "Reliance Health",
  },

  {
    name: "Acko Car Secure 1",
    type: "car",
    premium: 2500,
    coverage: 100000,
    riskLevel: "low",
    provider: "Acko",
  },
  {
    name: "ICICI Car Protect 2",
    type: "car",
    premium: 2700,
    coverage: 120000,
    riskLevel: "medium",
    provider: "ICICI Lombard",
  },
  {
    name: "Bajaj Auto Shield 3",
    type: "car",
    premium: 2900,
    coverage: 140000,
    riskLevel: "high",
    provider: "Bajaj Allianz",
  },
  {
    name: "HDFC Car Guard 4",
    type: "car",
    premium: 3100,
    coverage: 160000,
    riskLevel: "low",
    provider: "HDFC Ergo",
  },
  {
    name: "Tata Motor Protect 5",
    type: "car",
    premium: 3300,
    coverage: 180000,
    riskLevel: "medium",
    provider: "Tata AIG",
  },
  {
    name: "Car Plan 6",
    type: "car",
    premium: 3500,
    coverage: 200000,
    riskLevel: "high",
    provider: "Acko",
  },
  {
    name: "Car Plan 7",
    type: "car",
    premium: 3700,
    coverage: 220000,
    riskLevel: "low",
    provider: "ICICI Lombard",
  },
  {
    name: "Car Plan 8",
    type: "car",
    premium: 3900,
    coverage: 240000,
    riskLevel: "medium",
    provider: "Bajaj Allianz",
  },
  {
    name: "Car Plan 9",
    type: "car",
    premium: 4100,
    coverage: 260000,
    riskLevel: "high",
    provider: "HDFC Ergo",
  },
  {
    name: "Car Plan 10",
    type: "car",
    premium: 4300,
    coverage: 280000,
    riskLevel: "low",
    provider: "Tata AIG",
  },
  {
    name: "Car Plan 11",
    type: "car",
    premium: 4500,
    coverage: 300000,
    riskLevel: "medium",
    provider: "Acko",
  },
  {
    name: "Car Plan 12",
    type: "car",
    premium: 4700,
    coverage: 320000,
    riskLevel: "high",
    provider: "ICICI Lombard",
  },
  {
    name: "Car Plan 13",
    type: "car",
    premium: 4900,
    coverage: 340000,
    riskLevel: "low",
    provider: "Bajaj Allianz",
  },
  {
    name: "Car Plan 14",
    type: "car",
    premium: 5100,
    coverage: 360000,
    riskLevel: "medium",
    provider: "HDFC Ergo",
  },
  {
    name: "Car Plan 15",
    type: "car",
    premium: 5300,
    coverage: 380000,
    riskLevel: "high",
    provider: "Tata AIG",
  },
  {
    name: "Car Plan 16",
    type: "car",
    premium: 5500,
    coverage: 400000,
    riskLevel: "low",
    provider: "Acko",
  },
  {
    name: "Car Plan 17",
    type: "car",
    premium: 5700,
    coverage: 420000,
    riskLevel: "medium",
    provider: "ICICI Lombard",
  },
  {
    name: "Car Plan 18",
    type: "car",
    premium: 5900,
    coverage: 440000,
    riskLevel: "high",
    provider: "Bajaj Allianz",
  },
  {
    name: "Car Plan 19",
    type: "car",
    premium: 6100,
    coverage: 460000,
    riskLevel: "low",
    provider: "HDFC Ergo",
  },
  {
    name: "Car Plan 20",
    type: "car",
    premium: 6300,
    coverage: 480000,
    riskLevel: "medium",
    provider: "Tata AIG",
  },
  {
    name: "Car Plan 21",
    type: "car",
    premium: 6500,
    coverage: 500000,
    riskLevel: "high",
    provider: "Acko",
  },
  {
    name: "Car Plan 22",
    type: "car",
    premium: 6700,
    coverage: 520000,
    riskLevel: "low",
    provider: "ICICI Lombard",
  },
  {
    name: "Car Plan 23",
    type: "car",
    premium: 6900,
    coverage: 540000,
    riskLevel: "medium",
    provider: "Bajaj Allianz",
  },
  {
    name: "Car Plan 24",
    type: "car",
    premium: 7100,
    coverage: 560000,
    riskLevel: "high",
    provider: "HDFC Ergo",
  },
  {
    name: "Car Plan 25",
    type: "car",
    premium: 7300,
    coverage: 580000,
    riskLevel: "low",
    provider: "Tata AIG",
  },
  {
    name: "Car Plan 26",
    type: "car",
    premium: 7500,
    coverage: 600000,
    riskLevel: "medium",
    provider: "Acko",
  },
  {
    name: "Car Plan 27",
    type: "car",
    premium: 7700,
    coverage: 620000,
    riskLevel: "high",
    provider: "ICICI Lombard",
  },
  {
    name: "Car Plan 28",
    type: "car",
    premium: 7900,
    coverage: 640000,
    riskLevel: "low",
    provider: "Bajaj Allianz",
  },
  {
    name: "Car Plan 29",
    type: "car",
    premium: 8100,
    coverage: 660000,
    riskLevel: "medium",
    provider: "HDFC Ergo",
  },
  {
    name: "Car Plan 30",
    type: "car",
    premium: 8300,
    coverage: 680000,
    riskLevel: "high",
    provider: "Tata AIG",
  },
  {
    name: "Car Plan 31",
    type: "car",
    premium: 8500,
    coverage: 700000,
    riskLevel: "low",
    provider: "Acko",
  },
  {
    name: "Car Plan 32",
    type: "car",
    premium: 8700,
    coverage: 720000,
    riskLevel: "medium",
    provider: "ICICI Lombard",
  },
  {
    name: "Car Plan 33",
    type: "car",
    premium: 8900,
    coverage: 740000,
    riskLevel: "high",
    provider: "Bajaj Allianz",
  },
  {
    name: "Car Plan 34",
    type: "car",
    premium: 9100,
    coverage: 760000,
    riskLevel: "low",
    provider: "HDFC Ergo",
  },
  {
    name: "Car Plan 35",
    type: "car",
    premium: 9300,
    coverage: 780000,
    riskLevel: "medium",
    provider: "Tata AIG",
  },
  {
    name: "Car Plan 36",
    type: "car",
    premium: 9500,
    coverage: 800000,
    riskLevel: "high",
    provider: "Acko",
  },
  {
    name: "Car Plan 37",
    type: "car",
    premium: 9700,
    coverage: 820000,
    riskLevel: "low",
    provider: "ICICI Lombard",
  },
  {
    name: "Car Plan 38",
    type: "car",
    premium: 9900,
    coverage: 840000,
    riskLevel: "medium",
    provider: "Bajaj Allianz",
  },
  {
    name: "Car Plan 39",
    type: "car",
    premium: 10100,
    coverage: 860000,
    riskLevel: "high",
    provider: "HDFC Ergo",
  },
  {
    name: "Car Plan 40",
    type: "car",
    premium: 10300,
    coverage: 880000,
    riskLevel: "low",
    provider: "Tata AIG",
  },
  {
    name: "Car Plan 41",
    type: "car",
    premium: 10500,
    coverage: 900000,
    riskLevel: "medium",
    provider: "Acko",
  },
  {
    name: "Car Plan 42",
    type: "car",
    premium: 10700,
    coverage: 920000,
    riskLevel: "high",
    provider: "ICICI Lombard",
  },
  {
    name: "Car Plan 43",
    type: "car",
    premium: 10900,
    coverage: 940000,
    riskLevel: "low",
    provider: "Bajaj Allianz",
  },
  {
    name: "Car Plan 44",
    type: "car",
    premium: 11100,
    coverage: 960000,
    riskLevel: "medium",
    provider: "HDFC Ergo",
  },
  {
    name: "Car Plan 45",
    type: "car",
    premium: 11300,
    coverage: 980000,
    riskLevel: "high",
    provider: "Tata AIG",
  },
  {
    name: "Car Plan 46",
    type: "car",
    premium: 11500,
    coverage: 1000000,
    riskLevel: "low",
    provider: "Acko",
  },
  {
    name: "Car Plan 47",
    type: "car",
    premium: 11700,
    coverage: 1020000,
    riskLevel: "medium",
    provider: "ICICI Lombard",
  },
  {
    name: "Car Plan 48",
    type: "car",
    premium: 11900,
    coverage: 1040000,
    riskLevel: "high",
    provider: "Bajaj Allianz",
  },
  {
    name: "Car Plan 49",
    type: "car",
    premium: 12100,
    coverage: 1060000,
    riskLevel: "low",
    provider: "HDFC Ergo",
  },
  {
    name: "Car Plan 50",
    type: "car",
    premium: 12300,
    coverage: 1080000,
    riskLevel: "medium",
    provider: "Tata AIG",
  },
];

module.exports={data:samplePolicies};
