package com.suraksha.shield.controller;

import com.suraksha.shield.dto.PolicyOptimizationResult;
import com.suraksha.shield.entity.Policy;
import com.suraksha.shield.entity.User;
import com.suraksha.shield.repository.UserRepository;
import com.suraksha.shield.service.PolicyService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.web.bind.annotation.*;

import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;

@RestController
@RequestMapping("/api/policies")
@RequiredArgsConstructor
public class PolicyController {

    private final PolicyService policyService;
    private final UserRepository userRepository;

    @GetMapping("/{id}")
    public ResponseEntity<?> getPolicyDetail(@PathVariable Long id) {
        Policy policy = policyService.getPolicyById(id);
        return ResponseEntity.ok(policy);
    }

    @GetMapping("/results")
    public ResponseEntity<?> getOptimizationResults(
            @RequestParam(required = false) String name,
            @RequestParam(required = false) String type,
            @RequestParam(name = "riskLevel", required = false) String riskLevel,
            @RequestParam(name = "max_premium", required = false) Integer maxPremium,
            @RequestParam(name = "coverage_min", required = false) Integer coverageMin,
            @RequestParam(name = "coverage_max", required = false) Integer coverageMax,
            @RequestParam(name = "show_all", required = false) Boolean showAll) {

        if (showAll != null && showAll) {
            java.util.List<Policy> all = policyService.getAllPolicies();
            all.sort(java.util.Comparator.comparingInt(Policy::getPremium));
            PolicyOptimizationResult result = new PolicyOptimizationResult(all, false, 0, 0);
            return ResponseEntity.ok(result);
        }

        PolicyOptimizationResult result = policyService.optimize(type, riskLevel, name, maxPremium, coverageMin, coverageMax);
        return ResponseEntity.ok(result);
    }

    @PostMapping("/{id}/allocate")
    public ResponseEntity<?> allocatePolicy(@PathVariable Long id) {
        User user = getAuthenticatedUser();
        Policy policy = policyService.getPolicyById(id);

        Map<String, String> response = new HashMap<>();

        boolean alreadyAllocated = user.getAllocatedPolicies().stream()
                .anyMatch(p -> p.getId().equals(policy.getId()));

        if (alreadyAllocated) {
            response.put("message", "You have already allocated this policy.");
            return ResponseEntity.badRequest().body(response);
        }

        user.getAllocatedPolicies().add(policy);
        userRepository.save(user);

        response.put("message", "Policy successfully allocated to your profile!");
        return ResponseEntity.ok(response);
    }

    /**
     * Generates a plain-text policy summary as a downloadable PDF-like text file.
     * A full PDF library (iText/Apache PDFBox) can replace this for production.
     */
    @GetMapping("/{id}/download")
    public ResponseEntity<byte[]> downloadPolicySummary(@PathVariable Long id) {
        Policy policy = policyService.getPolicyById(id);

        double ratio = (policy.getCoverage() > 0)
                ? ((double) policy.getPremium() / policy.getCoverage()) * 100
                : 0;

        String content = String.format(
            "============================================================%n" +
            "          SURAKSHA SHIELD — POLICY SUMMARY%n" +
            "============================================================%n%n" +
            "Policy Name   : %s%n" +
            "Provider      : %s%n" +
            "Type          : %s Insurance%n" +
            "Risk Level    : %s%n%n" +
            "-------------------------------------------------------------%n" +
            "  CORE FINANCIALS%n" +
            "-------------------------------------------------------------%n" +
            "  Annual Premium     : INR %,d%n" +
            "  Total Coverage     : INR %,d%n" +
            "  Premium/Cover Ratio: %.2f%%%n%n" +
            "-------------------------------------------------------------%n" +
            "  RISK ANALYSIS%n" +
            "-------------------------------------------------------------%n" +
            "  Assessed Risk      : %s Level%n" +
            "  Provider Reliability: Excellent%n%n" +
            "============================================================%n" +
            "  Generated by Suraksha Shield | © 2026 Shreyas Kumbhar%n" +
            "============================================================%n",
            policy.getName(),
            policy.getProvider(),
            capitalize(policy.getType()),
            capitalize(policy.getRiskLevel()),
            policy.getPremium(),
            policy.getCoverage(),
            ratio,
            capitalize(policy.getRiskLevel())
        );

        byte[] bytes = content.getBytes(StandardCharsets.UTF_8);
        String filename = policy.getName().replaceAll("[^a-zA-Z0-9]", "_") + "_summary.txt";

        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + filename + "\"")
                .contentType(MediaType.TEXT_PLAIN)
                .contentLength(bytes.length)
                .body(bytes);
    }

    private User getAuthenticatedUser() {
        Object principal = SecurityContextHolder.getContext().getAuthentication().getPrincipal();
        String email = (principal instanceof UserDetails)
                ? ((UserDetails) principal).getUsername()
                : principal.toString();
        return userRepository.findByEmail(email)
                .orElseThrow(() -> new RuntimeException("User not found"));
    }

    private String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1).toLowerCase();
    }
}
