// Schema of every policy
const mongoose = require("mongoose");

const Schema = mongoose.Schema;
const PolicySchema=new Schema({
    name:{
        type:String,
        required:true,
    },
    type:{
        type:String,
        required:true,
    },
    premium:{
        type:Number,
        required:true,
    },
    coverage:{
        type:Number,
        required:true,
    },
    riskLevel:{
        type:String,
        required:true,
    },
    provider:{
        type:String,
        required:true,
    },
    createdBy: {
        type: Schema.Types.ObjectId,
        ref: "Admin"
    }
    

});

const Policy=mongoose.model("Policy",PolicySchema);//policy is new model we need to export
module.exports=Policy; //collection will be automatic generated by model name

